"Un producto que tiene un identificador, un nombre, un precio, categoria, coste"
"Tienda de muebles ikea"
"Hacemos clase para representar en codigo, la informacion que tenemos en una base de datos"
"Armario {puerta, color, dimensiones, altura, ancho},"
"Silla {patas, material, color}"